### ISSUE TITLE
When I downloaded the data, I found that the link was invalid,would you please replace it?

### ISSUE THREAD

**Issue by thingswelike11** [ZedFm/FDCN_FDRN#1]
When I downloaded the data, I found that the link was invalid,would you please replace it?
Thanks!

**Comment by ZedFm** [comment]
I uploaded the data and the pre-trained models in another link, may be you can have a new try, thanks.

**Comment by ZedFm** [comment]
https://drive.google.com/file/d/1xV7iCuQxGroAsB3Cxdwi-IqgbHVC2aXI/view?usp=sharing

**Comment by ewjfjfnfdsv** [comment]
We also cannot download the data from the new Google Drive link you provided. Could you please update the link again? This is crucial for our research, thank you once again.

**Comment by ZedFm** [comment]
Now the link is updated,.

https://drive.google.com/file/d/1vo25UKvMrFQOoyk5m9w9wpJUEMSUcl_W/view?usp=drive_link

Hope everything goes well,
